### ISSUE TITLE
Open error

### ISSUE THREAD

**Issue by zhutaorun** [skyteks/WarKingdoms#2]
![image](https://user-images.githubusercontent.com/11263591/168463470-72637b66-c289-446f-b6dd-a8617d50cc2d.png)

Unity 2020.3.7f1c1

**Comment by skyteks** [comment]
Oh thanks for the info.
You need A* Pro from the assetstore 
https://assetstore.unity.com/packages/tools/ai/a-pathfinding-project-pro-87744
Forgot to reference that in the Readme.md, because I am not sure if I want to use it.
I only added that for a test.

**Comment by skyteks** [comment]
I removed A* Pro, so this should be fixed.
